name: 'Download From list'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        sudo apt install ffmpeg
        pip install .
        mkdir downloaded
    - name: Decrypt cookies
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.COOKIE_PASSPHASE }}" --output ./downloaded/cookies.txt cookies.txt.gpg
    - name: Download songs
      run: |
        cd downloaded
        spotdl download query 1 --cookie-file ../cookies.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: songs
        path: "./downloaded/"
