name: 'Download From list'
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt install ffmpeg
        chmod +x ./scripts/termux.sh
        ./scripts/termux.sh
    - name: Download songs
      run: |
        mkdir downloaded
        cd downloaded
        spotdl download query 1
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: songs
        path: "./downloaded/"
